site_name: Jetplot
site_url: https://github.com/nirum/jetplot
repo_url: https://github.com/nirum/jetplot

nav:
  - Home: index.md
  - Description: description.md
  - API:
    - Chart Utils: api/chart_utils.md
    - Plots: api/plots.md
    - Images: api/images.md
    - Colors: api/colors.md
    - Style: api/style.md
    - Signals: api/signals.md
    - Timepiece: api/timepiece.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          options:
            show_source: true
            show_signature_annotations: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
